use titanic;
show tables;
select * from p_info;
select Name from p_info;
select Name, Age from p_info;
desc p_info;
select * from p_info limit 10;
select * from p_info where Sex="male";
select * from p_info where Age>40;
select * from p_info where Sex="male" and Age<10;
select * from p_info where Sex="male" or Age<10;
select * from p_info where Age>=20 and Age<50 and Sex="female"; 
select * from p_info where SibSp=1 or Parch>=1;
select * from p_info where Pclass=1;
desc p_info;
SELECT * from t_info where Pclass=1;
select * from t_info where Pclass=2 and Fare>50;
select * from survived where survived=1;
select * from p_info where SibSp in(1, 2, 3);
select * from p_info where SibSp not in(0, 1, 2, 3);
select * from p_info where name LIKE "Rice%";
select * from p_info where name LIKE "%Eric";
select * from p_info where name LIKE "%Oscar%";
select * from p_info where Age BETWEEN 20 and 40;
SELECT * FROM p_info where Age is null;
select * from t_info where Fare between 100 and 1000;
select * from t_info where Ticket like "PC%" AND Embarked="C" OR "S";
select * from t_info where Pclass in(1, 2);
select * from t_info where Cabin LIKE "%59%";
SELECT * FROM p_info where Age is not null and Name like "%james%" and Age>=40 and Sex="male";
SELECT * FROM P_INFO WHERE Age is not null and Name like"%Miss%" and Age <=40 and Sex="female" ORDER BY Age DESC;
SELECT SEX, AVG(Age) from p_info where Age is not null GROUP BY Sex;
SELECT Pclass, AVG(Fare) from t_info group by Pclass having AVG(Fare) > 50;
select * from passenger limit 3;
select * from ticket limit 3;
select * from passenger inner join ticket on passenger.passengerId = ticket.passengerId;
select * from passenger left join ticket on passenger.passengerId = ticket.passengerId;
select * from passenger right join ticket on passenger.passengerId = ticket.passengerId;
select Name, Age, Pclass, Fare from passenger inner join ticket on passenger.passengerId = ticket.passengerId;
select Name, Age, Pclass, Fare from passenger inner join ticket on passenger.passengerId = ticket.passengerId;
select * from passenger inner join ticket on passenger.passengerId = ticket.passengerId inner join survived on passenger.passengerId = survived.passengerId;
select Name, Age, Sex, Pclass, Survived from passenger inner join 