# 날짜 형식 바꾸기
DATE_FORMAT(DATE_OF_BIRTH, "%y-%m-%d") as DATE_OF_BIRTH

# 프로그래머스 SQL SELECT
# 3월에 태어난 여성 회원 목록 출력하기
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH from MEMBER_PROFILE 
WHERE DATE_OF_BIRTH LIKE "%03%" AND GENDER="W" AND TLNO IS NOT NULL ORDER BY MEMBER_ID ASC;

# 재구매가 일어난 상품과 회원 리스트 구하기
SELECT USER_ID, PRODUCT_ID FROM ONLINE_SALE 
GROUP BY USER_ID, PRODUCT_ID HAVING COUNT(USER_ID)>1
ORDER BY USER_ID ASC, PRODUCT_ID DESC;

# 역순 정렬하기
SELECT NAME, DATETIME FROM ANIMAL_INS ORDER BY ANIMAL_ID DESC;

# 아픈 동물 찾기
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION="SICK" ORDER BY ANIMAL_ID ASC;

# 어린 동물 찾기
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE NOT INTAKE_CONDITION="AGED" ORDER BY ANIMAL_ID ASC;

# 동물의 아이디와 이름
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS ORDER BY ANIMAL_ID ASC;

# 여러 기준으로 정렬하기
SELECT ANIMAL_ID, NAME, DATETIME FROM ANIMAL_INS ORDER BY NAME ASC, DATETIME DESC;

# 상위 n개 레코드
SELECT NAME FROM ANIMAL_INS ORDER BY DATETIME ASC LIMIT 1;

# 조건에 맞는 회원수 구하기
SELECT COUNT(USER_ID) USERS FROM USER_INFO WHERE JOINED LIKE '%2021%' AND AGE BETWEEN 20 AND 29;

# 흉부외과 또는 일반외과 의사 목록 출력하기
SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD, "%Y-%m-%d") as HIRE_YMD FROM DOCTOR
WHERE MCDP_CD in ("cs", "gs") ORDER BY HIRE_YMD DESC, DR_NAME ASC;

# 과일로 만든 아이스크림 고르기, melon이 없다.
select ICECREAM_INFO.FLAVOR from FIRST_HALF left join ICECREAM_INFO 
on FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
where TOTAL_ORDER>3000 and INGREDIENT_TYPE="fruit_based" order by TOTAL_ORDER desc;

# 평균 일일 대여 요금 구하기
SELECT round(avg(daily_fee)) AVERAGE_FEE from CAR_RENTAL_COMPANY_CAR where car_type="SUV";

# 강원도에 위치한 생산공장 목록 출력하기
SELECT FACTORY_ID, FACTORY_NAME, ADDRESS from FOOD_FACTORY where ADDRESS like "%강원도%" order by FACTORY_ID asc;

# 인기있는 아이스크림
SELECT FLAVOR from FIRST_HALF order by TOTAL_ORDER desc, SHIPMENT_ID asc;

# 12세 이하인 여자 환자 목록 출력하기
# 블랭크를 표기하는 방식 COALESCE(columm, 입력문)
SELECT PT_NAME, PT_NO, GEND_CD, AGE, COALESCE(TLNO, "NONE") from PATIENT where GEND_CD="W" AND AGE<=12 order by AGE desc, PT_NAME asc;

# 조건에 맞는 도서 리스트 출력하기
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, "%Y-%m-%d") as PUBLISHED_DATE FROM BOOK WHERE PUBLISHED_DATE LIKE "%2021%" AND CATEGORY="인문" ORDER BY PUBLISHED_DATE ASC;

# 조건에 부합하는 중고거래 댓글 조회하기

